// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pooled connection — used by the app at runtime (serverless-safe).
    url: process.env["DATABASE_URL"],
    // Direct (non-pooled) connection — used by migrations / db push.
    // Neon's pooler can't hold the session locks the migrate engine needs.
    directUrl: process.env["DIRECT_URL"],
  },
});
