// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // This URL is used ONLY by the Prisma CLI (migrate / db push). Prefer the
    // direct (non-pooled) connection — Neon's pooler can't hold the session locks
    // the migrate engine needs (D10). The app itself connects via the pg driver
    // adapter in lib/db.ts using the pooled DATABASE_URL (serverless-safe).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
